name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Publish Worker with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          command: publish
          workingDirectory: apps/worker
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Prefer OIDC (Workload Identity) if your Cloudflare account is configured.
          # Otherwise, set CLOUDFLARE_API_TOKEN in repo secrets with minimal scopes.
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-pages:
    name: Deploy Pages (Admin UI)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build UI
        working-directory: apps/admin-ui
        run: |
          npm ci || npm install
          npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ai-market-intel-admin
          directory: apps/admin-ui/dist
